### PR TITLE
Fix setting public property with private setter #102

### PR DESCRIPTION
**Pull request by jaymclain**
Use GetSetMethod() to discriminate between properties that "can" be written (e.g. public property) and properties that "should" be written (e.g. public property with public getter)

### CODE REVIEW

**Comment by Doug-Murphy** [comment]
@jaymclain There are a few other locations where `CanWrite` is used. Should those also be updated?

**Comment by Doug-Murphy** [comment]
Fixes #102

**Comment by crmckenzie** [comment]
Help me understand why this is important and what it fixes please.

**Comment by jaymclain** [comment]
If my description in the linked issue didn't describe why it was important, and what it fixes, please see the specific example I added to #102.

**Pull request merged**
